### ISSUE TITLE
TOTK Version 1.2.0 Causes Yuzu to Be Stuck in "Launching"

### ISSUE THREAD

**Issue by baltimoresports** [jordanbtucker/totk-no-loot-boxes#22]
Plugin: 2.0.1
TOTK: 1.2.0
OS: Windows 11
Yuzu: 1494

**Comment by jordanbtucker** [comment]
Thanks for reporting this. The file that this mod updates was changed in v1.2.0, so I'll need to make a new version of the mod for v1.2.0. I'll do that today.

**Comment by jordanbtucker** [comment]
Fixed in [v3.0.0](https://github.com/jordanbtucker/totk-no-loot-boxes/releases/tag/v3.0.0).

**Comment by baltimoresports** [comment]
Thank you sir!
